# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CoffeHouse' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CoffeHouse

  target 'CoffeHouseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CoffeHouseUITests' do
    # Pods for testing
  end

end
